name: scopely
description: Provides tools to let you enhance Dart's `async`/`await` model the way you want to.
version: 1.1.7
repository: https://github.com/skylon07/scopely

environment:
  sdk: ^3.7.2

dependencies:
  # should NOT depend on Flutter or Flutter-dependent packages;
  # this package should be usable by pure Dart applications
  # flutter: ...

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
